services:
  redis:
    image: redis/redis-stack-server:latest
    command: ["redis-server", "--appendonly yes", "--save 60 1000",  "--requirepass redisPassword"]
    ports:
      - 127.0.0.1:6379:6379
    tmpfs:
      - /data
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=budget_app
      - POSTGRES_USER=budget_app
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=UTC
    ports:
      - 127.0.0.1:5432:5432
    tmpfs:
      - /var/lib/postgresql/data
