http:
  port: 3987

jwt:
  secret: 'Some secret'
  expirationSec: 60

postgres:
  host: 127.0.0.1
  port: 5432
  database: 'budget_app'
  username: 'budget_app'
  synchronize: true

redis:
  host: 127.0.0.1
  port: 6379
